function dydt = EGFR_NFkB_ver_01_ode_std(t, y, p)
%% EGFR_NFkB_ver_01_ode_std - MATLAB Standard ODE Solver Compatible ODE Function
%
% Generated by ODE Model Creator
% Model: EGFR_NFkB_ver_01
% Date: 15-Jan-2026 17:42:41
%
% Usage:
%   p = EGFR_NFkB_ver_01_ode_std('parameters');  % Get default parameters
%   y0 = EGFR_NFkB_ver_01_ode_std('initialvalues');  % Get default initial values
%   [t, y] = ode15s(@(t,y) EGFR_NFkB_ver_01_ode_std(t, y, p), [0 1000], y0);
%
% State Variables (48):
%   y(1) = AKT
%   y(2) = AKT_p
%   y(3) = AP1
%   y(4) = AP1_a
%   y(5) = AURKA
%   y(6) = AURKAm
%   y(7) = COX2
%   y(8) = COX2m
%   y(9) = EGF
%   y(10) = EGFR
%   y(11) = EGFR_p
%   y(12) = EGFm
%   y(13) = ERK
%   y(14) = ERK_p
%   y(15) = IKB
%   y(16) = IKBm
%   y(17) = IKK
%   y(18) = IKK_a
%   y(19) = IL6
%   y(20) = IL6m
%   y(21) = JAK
%   y(22) = JAK_a
%   y(23) = Myc
%   y(24) = NFkB
%   y(25) = NFkBnIKB
%   y(26) = PGE2
%   y(27) = PI3K
%   y(28) = PI3K_a
%   y(29) = PIP2
%   y(30) = PIP3
%   y(31) = PKC
%   y(32) = PKC_a
%   y(33) = PTEN
%   y(34) = RAS
%   y(35) = RAS_a
%   y(36) = STAT3
%   y(37) = STAT3_p
%   y(38) = TNFR1
%   y(39) = TNFR1_a
%   y(40) = TNFR1_p
%   y(41) = TNFa
%   y(42) = TNFam
%   y(43) = TTP
%   y(44) = ZFP36
%   y(45) = mTORC1
%   y(46) = mTORC1_a
%   y(47) = mTORC2
%   y(48) = mTORC2_a
%

% Handle metadata requests
if nargin == 1 && ischar(t)
    switch lower(t)
        case 'parameters'
            dydt = [0.1   0.1   0.1   0.1   0.1  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05   100 10000]';
            return;
        case 'parameternames'
            dydt = {'Ki_PI3K_PI3K_a_EGFR_p_OSM'; 'Ki_PKC_PKC_a_EGFR_p_OSM'; 'Ki_RAS_RAS_a_EGFR_p_OSM'; 'Ki_TNFR1_TNFR1_p_EGFR_p_OSM'; 'Ki_syn_PTEN_NFkB'; 'Vm_AKT_p_AKT'; 'Vm_AP1_a_AP1'; 'Vm_EGFR_p_EGFR'; 'Vm_ERK_p_ERK'; 'Vm_IKK_a_IKK'; 'Vm_JAK_a_JAK'; 'Vm_PI3K_a_PI3K'; 'Vm_PIP2_PIP3'; 'Vm_PIP3_PIP2'; 'Vm_PKC_a_PKC'; 'Vm_RAS_a_RAS'; 'Vm_STAT3_p_STAT3'; 'Vm_TNFR1_a_TNFR1'; 'Vm_TNFR1_p_TNFR1'; 'Vm_mTORC1_a_mTORC1'; 'Vm_mTORC2_a_mTORC2'; 'Vsyn_AURKAm'; 'Vsyn_COX2m'; 'Vsyn_EGFm'; 'Vsyn_IKBm'; 'Vsyn_IL6m'; 'Vsyn_Myc'; 'Vsyn_NFkB'; 'Vsyn_PGE2'; 'Vsyn_PTEN'; 'Vsyn_TNFam'; 'Vsyn_ZFP36'; 'ka_IKB_NFkB_NFkBnIKB'; 'kalpha_COX2m_NFkB_STAT3_p'; 'kalpha_EGFm_NFkB_STAT3_p'; 'kalpha_IKBm_NFkB_STAT3_p'; 'kalpha_IL6m_NFkB_STAT3_p'; 'kalpha_TNFam_NFkB_STAT3_p'; 'kalpha_ZFP36_NFkB_STAT3_p'; 'kc_AKT_AKT_p_PI3K_a'; 'kc_AKT_AKT_p_mTORC2_a'; 'kc_AP1_AP1_a_ERK_p'; 'kc_EGFR_EGFR_p_EGF'; 'kc_ERK_ERK_p_RAS_a'; 'kc_IKK_IKK_a_AKT_p'; 'kc_IKK_IKK_a_PKC_a'; 'kc_IKK_IKK_a_TNFR1_a'; 'kc_JAK_JAK_a_EGFR_p'; 'kc_JAK_JAK_a_IL6'; 'kc_PI3K_PI3K_a_EGFR_p'; 'kc_PIP2_PIP3_PI3K_a'; 'kc_PIP3_PIP2_PTEN'; 'kc_PKC_PKC_a_EGFR_p'; 'kc_PKC_PKC_a_PGE2'; 'kc_RAS_RAS_a_EGFR_p'; 'kc_STAT3_STAT3_p_JAK_a'; 'kc_TNFR1_TNFR1_a_TNFa'; 'kc_TNFR1_TNFR1_p_EGFR_p'; 'kc_mTORC1_mTORC1_a_AKT_p'; 'kc_mTORC2_mTORC2_a_IKK_a'; 'kd_NFkBnIKB_IKB_NFkB'; 'kdeg_AURKA'; 'kdeg_AURKAm'; 'kdeg_COX2'; 'kdeg_COX2m'; 'kdeg_EGF'; 'kdeg_EGFm'; 'kdeg_IKB'; 'kdeg_IKB_AURKA'; 'kdeg_IKB_IKK_a'; 'kdeg_IKBm'; 'kdeg_IL6'; 'kdeg_IL6m'; 'kdeg_IL6m_TTP'; 'kdeg_Myc'; 'kdeg_NFkB'; 'kdeg_NFkB_TTP'; 'kdeg_PGE2'; 'kdeg_PTEN'; 'kdeg_TNFa'; 'kdeg_TNFam'; 'kdeg_TNFam_TTP'; 'kdeg_TTP'; 'kdeg_ZFP36'; 'ksyn_AURKA_AURKAm'; 'ksyn_AURKAm_Myc'; 'ksyn_COX2_COX2m'; 'ksyn_COX2m_NFkB'; 'ksyn_EGF_EGFm'; 'ksyn_EGFm_AP1_a'; 'ksyn_EGFm_NFkB'; 'ksyn_IKB_IKBm'; 'ksyn_IKBm_NFkB'; 'ksyn_IL6_IL6m'; 'ksyn_IL6m_NFkB'; 'ksyn_Myc_mTORC1_a'; 'ksyn_PGE2_COX2'; 'ksyn_TNFa_TNFam'; 'ksyn_TNFam_NFkB'; 'ksyn_TTP_ZFP36'; 'ksyn_ZFP36_NFkB'; 'OSM_0'; 'OSM_on'}';
            return;
        case 'initialvalues'
            dydt = [51 91 25 41 76 23  7 29 16 93 81 63 88 81 18 90 54 81 90 32 11 23 43 82 86  0 51 42 22 12 34 95 32 52 71 36 98 97 25 50 30 28  3 61 50  5 28 91]';
            return;
        case 'statenames'
            dydt = {'AKT'; 'AKT_p'; 'AP1'; 'AP1_a'; 'AURKA'; 'AURKAm'; 'COX2'; 'COX2m'; 'EGF'; 'EGFR'; 'EGFR_p'; 'EGFm'; 'ERK'; 'ERK_p'; 'IKB'; 'IKBm'; 'IKK'; 'IKK_a'; 'IL6'; 'IL6m'; 'JAK'; 'JAK_a'; 'Myc'; 'NFkB'; 'NFkBnIKB'; 'PGE2'; 'PI3K'; 'PI3K_a'; 'PIP2'; 'PIP3'; 'PKC'; 'PKC_a'; 'PTEN'; 'RAS'; 'RAS_a'; 'STAT3'; 'STAT3_p'; 'TNFR1'; 'TNFR1_a'; 'TNFR1_p'; 'TNFa'; 'TNFam'; 'TTP'; 'ZFP36'; 'mTORC1'; 'mTORC1_a'; 'mTORC2'; 'mTORC2_a'}';
            return;
        otherwise
            error('Unknown request: %s', t);
    end
end

% Use default parameters if not provided
if nargin < 3 || isempty(p)
    p = [0.1   0.1   0.1   0.1   0.1  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05   100 10000]';
end

% ==========================================
% STATE VARIABLES
% ==========================================
AKT = y(1);
AKT_p = y(2);
AP1 = y(3);
AP1_a = y(4);
AURKA = y(5);
AURKAm = y(6);
COX2 = y(7);
COX2m = y(8);
EGF = y(9);
EGFR = y(10);
EGFR_p = y(11);
EGFm = y(12);
ERK = y(13);
ERK_p = y(14);
IKB = y(15);
IKBm = y(16);
IKK = y(17);
IKK_a = y(18);
IL6 = y(19);
IL6m = y(20);
JAK = y(21);
JAK_a = y(22);
Myc = y(23);
NFkB = y(24);
NFkBnIKB = y(25);
PGE2 = y(26);
PI3K = y(27);
PI3K_a = y(28);
PIP2 = y(29);
PIP3 = y(30);
PKC = y(31);
PKC_a = y(32);
PTEN = y(33);
RAS = y(34);
RAS_a = y(35);
STAT3 = y(36);
STAT3_p = y(37);
TNFR1 = y(38);
TNFR1_a = y(39);
TNFR1_p = y(40);
TNFa = y(41);
TNFam = y(42);
TTP = y(43);
ZFP36 = y(44);
mTORC1 = y(45);
mTORC1_a = y(46);
mTORC2 = y(47);
mTORC2_a = y(48);

% ==========================================
% PARAMETERS
% ==========================================
Ki_PI3K_PI3K_a_EGFR_p_OSM = p(1);
Ki_PKC_PKC_a_EGFR_p_OSM = p(2);
Ki_RAS_RAS_a_EGFR_p_OSM = p(3);
Ki_TNFR1_TNFR1_p_EGFR_p_OSM = p(4);
Ki_syn_PTEN_NFkB = p(5);
Vm_AKT_p_AKT = p(6);
Vm_AP1_a_AP1 = p(7);
Vm_EGFR_p_EGFR = p(8);
Vm_ERK_p_ERK = p(9);
Vm_IKK_a_IKK = p(10);
Vm_JAK_a_JAK = p(11);
Vm_PI3K_a_PI3K = p(12);
Vm_PIP2_PIP3 = p(13);
Vm_PIP3_PIP2 = p(14);
Vm_PKC_a_PKC = p(15);
Vm_RAS_a_RAS = p(16);
Vm_STAT3_p_STAT3 = p(17);
Vm_TNFR1_a_TNFR1 = p(18);
Vm_TNFR1_p_TNFR1 = p(19);
Vm_mTORC1_a_mTORC1 = p(20);
Vm_mTORC2_a_mTORC2 = p(21);
Vsyn_AURKAm = p(22);
Vsyn_COX2m = p(23);
Vsyn_EGFm = p(24);
Vsyn_IKBm = p(25);
Vsyn_IL6m = p(26);
Vsyn_Myc = p(27);
Vsyn_NFkB = p(28);
Vsyn_PGE2 = p(29);
Vsyn_PTEN = p(30);
Vsyn_TNFam = p(31);
Vsyn_ZFP36 = p(32);
ka_IKB_NFkB_NFkBnIKB = p(33);
kalpha_COX2m_NFkB_STAT3_p = p(34);
kalpha_EGFm_NFkB_STAT3_p = p(35);
kalpha_IKBm_NFkB_STAT3_p = p(36);
kalpha_IL6m_NFkB_STAT3_p = p(37);
kalpha_TNFam_NFkB_STAT3_p = p(38);
kalpha_ZFP36_NFkB_STAT3_p = p(39);
kc_AKT_AKT_p_PI3K_a = p(40);
kc_AKT_AKT_p_mTORC2_a = p(41);
kc_AP1_AP1_a_ERK_p = p(42);
kc_EGFR_EGFR_p_EGF = p(43);
kc_ERK_ERK_p_RAS_a = p(44);
kc_IKK_IKK_a_AKT_p = p(45);
kc_IKK_IKK_a_PKC_a = p(46);
kc_IKK_IKK_a_TNFR1_a = p(47);
kc_JAK_JAK_a_EGFR_p = p(48);
kc_JAK_JAK_a_IL6 = p(49);
kc_PI3K_PI3K_a_EGFR_p = p(50);
kc_PIP2_PIP3_PI3K_a = p(51);
kc_PIP3_PIP2_PTEN = p(52);
kc_PKC_PKC_a_EGFR_p = p(53);
kc_PKC_PKC_a_PGE2 = p(54);
kc_RAS_RAS_a_EGFR_p = p(55);
kc_STAT3_STAT3_p_JAK_a = p(56);
kc_TNFR1_TNFR1_a_TNFa = p(57);
kc_TNFR1_TNFR1_p_EGFR_p = p(58);
kc_mTORC1_mTORC1_a_AKT_p = p(59);
kc_mTORC2_mTORC2_a_IKK_a = p(60);
kd_NFkBnIKB_IKB_NFkB = p(61);
kdeg_AURKA = p(62);
kdeg_AURKAm = p(63);
kdeg_COX2 = p(64);
kdeg_COX2m = p(65);
kdeg_EGF = p(66);
kdeg_EGFm = p(67);
kdeg_IKB = p(68);
kdeg_IKB_AURKA = p(69);
kdeg_IKB_IKK_a = p(70);
kdeg_IKBm = p(71);
kdeg_IL6 = p(72);
kdeg_IL6m = p(73);
kdeg_IL6m_TTP = p(74);
kdeg_Myc = p(75);
kdeg_NFkB = p(76);
kdeg_NFkB_TTP = p(77);
kdeg_PGE2 = p(78);
kdeg_PTEN = p(79);
kdeg_TNFa = p(80);
kdeg_TNFam = p(81);
kdeg_TNFam_TTP = p(82);
kdeg_TTP = p(83);
kdeg_ZFP36 = p(84);
ksyn_AURKA_AURKAm = p(85);
ksyn_AURKAm_Myc = p(86);
ksyn_COX2_COX2m = p(87);
ksyn_COX2m_NFkB = p(88);
ksyn_EGF_EGFm = p(89);
ksyn_EGFm_AP1_a = p(90);
ksyn_EGFm_NFkB = p(91);
ksyn_IKB_IKBm = p(92);
ksyn_IKBm_NFkB = p(93);
ksyn_IL6_IL6m = p(94);
ksyn_IL6m_NFkB = p(95);
ksyn_Myc_mTORC1_a = p(96);
ksyn_PGE2_COX2 = p(97);
ksyn_TNFa_TNFam = p(98);
ksyn_TNFam_NFkB = p(99);
ksyn_TTP_ZFP36 = p(100);
ksyn_ZFP36_NFkB = p(101);
OSM_0 = p(102);
OSM_on = p(103);

% ==========================================
% INPUT SIGNALS AND INHIBITORS
% ==========================================
OSM = OSM_0 * piecewise_std(1, ge(t, OSM_on), 0);

% ==========================================
% REACTION RATES
% ==========================================
R1 = (kc_AKT_AKT_p_PI3K_a*PI3K_a+kc_AKT_AKT_p_mTORC2_a*mTORC2_a)*AKT - Vm_AKT_p_AKT*AKT_p;
R2 = (kc_AP1_AP1_a_ERK_p*ERK_p)*AP1 - Vm_AP1_a_AP1*AP1_a;
R3 = kdeg_AURKA*AURKA;
R4 = (ksyn_AURKA_AURKAm*AURKAm);
R5 = kdeg_AURKAm*AURKAm;
R6 = Vsyn_AURKAm;
R7 = (ksyn_AURKAm_Myc*Myc);
R8 = kdeg_COX2*COX2;
R9 = (ksyn_COX2_COX2m*COX2m);
R10 = kdeg_COX2m*COX2m;
R11 = Vsyn_COX2m;
R12 = (ksyn_COX2m_NFkB*NFkB*(1 + kalpha_COX2m_NFkB_STAT3_p*STAT3_p));
R13 = kdeg_EGF*EGF;
R14 = (ksyn_EGF_EGFm*EGFm);
R15 = kdeg_EGFm*EGFm;
R16 = Vsyn_EGFm;
R17 = (ksyn_EGFm_NFkB*NFkB*(1 + kalpha_EGFm_NFkB_STAT3_p*STAT3_p));
R18 = (ksyn_EGFm_AP1_a*AP1_a);
R19 = (kc_EGFR_EGFR_p_EGF*EGF)*EGFR - Vm_EGFR_p_EGFR*EGFR_p;
R20 = (kc_ERK_ERK_p_RAS_a*RAS_a)*ERK - Vm_ERK_p_ERK*ERK_p;
R21 = (ka_IKB_NFkB_NFkBnIKB*IKB*NFkB) - kd_NFkBnIKB_IKB_NFkB*NFkBnIKB;
R22 = kdeg_IKB*IKB;
R23 = (kdeg_IKB_IKK_a*IKB*IKK_a+kdeg_IKB_AURKA*IKB*AURKA);
R24 = (ksyn_IKB_IKBm*IKBm);
R25 = kdeg_IKBm*IKBm;
R26 = Vsyn_IKBm;
R27 = (ksyn_IKBm_NFkB*NFkB*(1 + kalpha_IKBm_NFkB_STAT3_p*STAT3_p));
R28 = (kc_IKK_IKK_a_TNFR1_a*TNFR1_a+kc_IKK_IKK_a_PKC_a*PKC_a+kc_IKK_IKK_a_AKT_p*AKT_p)*IKK - Vm_IKK_a_IKK*IKK_a;
R29 = kdeg_IL6*IL6;
R30 = (ksyn_IL6_IL6m*IL6m);
R31 = kdeg_IL6m*IL6m;
R32 = (kdeg_IL6m_TTP*IL6m*TTP);
R33 = Vsyn_IL6m;
R34 = (ksyn_IL6m_NFkB*NFkB*(1 + kalpha_IL6m_NFkB_STAT3_p*STAT3_p));
R35 = (kc_JAK_JAK_a_IL6*IL6+kc_JAK_JAK_a_EGFR_p*EGFR_p)*JAK - Vm_JAK_a_JAK*JAK_a;
R36 = (kc_mTORC1_mTORC1_a_AKT_p*AKT_p)*mTORC1 - Vm_mTORC1_a_mTORC1*mTORC1_a;
R37 = (kc_mTORC2_mTORC2_a_IKK_a*IKK_a)*mTORC2 - Vm_mTORC2_a_mTORC2*mTORC2_a;
R38 = kdeg_Myc*Myc;
R39 = Vsyn_Myc;
R40 = (ksyn_Myc_mTORC1_a*mTORC1_a);
R41 = Vsyn_NFkB;
R42 = kdeg_NFkB*NFkB;
R43 = (kdeg_NFkB_TTP*NFkB*TTP);
R44 = kdeg_PGE2*PGE2;
R45 = Vsyn_PGE2;
R46 = (ksyn_PGE2_COX2*COX2);
R47 = (kc_PI3K_PI3K_a_EGFR_p*EGFR_p)*PI3K/((1 + Ki_PI3K_PI3K_a_EGFR_p_OSM*OSM)) - Vm_PI3K_a_PI3K*PI3K_a;
R48 = (kc_PIP2_PIP3_PI3K_a*PI3K_a)*PIP2 - Vm_PIP3_PIP2*PIP3;
R49 = (kc_PIP3_PIP2_PTEN*PTEN)*PIP3 - Vm_PIP2_PIP3*PIP2;
R50 = (kc_PKC_PKC_a_EGFR_p*EGFR_p)*PKC/((1 + Ki_PKC_PKC_a_EGFR_p_OSM*OSM)) - Vm_PKC_a_PKC*PKC_a;
R51 = (kc_PKC_PKC_a_PGE2*PGE2)*PKC - Vm_PKC_a_PKC*PKC_a;
R52 = kdeg_PTEN*PTEN;
R53 = Vsyn_PTEN/((1 + Ki_syn_PTEN_NFkB*NFkB));
R54 = (kc_RAS_RAS_a_EGFR_p*EGFR_p)*RAS/((1 + Ki_RAS_RAS_a_EGFR_p_OSM*OSM)) - Vm_RAS_a_RAS*RAS_a;
R55 = (kc_STAT3_STAT3_p_JAK_a*JAK_a)*STAT3 - Vm_STAT3_p_STAT3*STAT3_p;
R56 = kdeg_TNFa*TNFa;
R57 = (ksyn_TNFa_TNFam*TNFam);
R58 = kdeg_TNFam*TNFam;
R59 = (kdeg_TNFam_TTP*TNFam*TTP);
R60 = Vsyn_TNFam;
R61 = (ksyn_TNFam_NFkB*NFkB*(1 + kalpha_TNFam_NFkB_STAT3_p*STAT3_p));
R62 = (kc_TNFR1_TNFR1_a_TNFa*TNFa)*TNFR1 - Vm_TNFR1_a_TNFR1*TNFR1_a;
R63 = (kc_TNFR1_TNFR1_p_EGFR_p*EGFR_p)*TNFR1/((1 + Ki_TNFR1_TNFR1_p_EGFR_p_OSM*OSM)) - Vm_TNFR1_p_TNFR1*TNFR1_p;
R64 = kdeg_TTP*TTP;
R65 = (ksyn_TTP_ZFP36*ZFP36);
R66 = kdeg_ZFP36*ZFP36;
R67 = Vsyn_ZFP36;
R68 = (ksyn_ZFP36_NFkB*NFkB*(1 + kalpha_ZFP36_NFkB_STAT3_p*STAT3_p));

% ==========================================
% DIFFERENTIAL EQUATIONS
% ==========================================
dydt = zeros(48, 1);
dydt(1) = -R1;  % AKT
dydt(2) = R1;  % AKT_p
dydt(3) = -R2;  % AP1
dydt(4) = R2;  % AP1_a
dydt(5) = -R3 +R4;  % AURKA
dydt(6) = -R5 +R6 +R7;  % AURKAm
dydt(7) = -R8 +R9;  % COX2
dydt(8) = -R10 +R11 +R12;  % COX2m
dydt(9) = -R13 +R14;  % EGF
dydt(10) = -R19;  % EGFR
dydt(11) = R19;  % EGFR_p
dydt(12) = -R15 +R16 +R17 +R18;  % EGFm
dydt(13) = -R20;  % ERK
dydt(14) = R20;  % ERK_p
dydt(15) = -R21 -R22 -R23 +R24;  % IKB
dydt(16) = -R25 +R26 +R27;  % IKBm
dydt(17) = -R28;  % IKK
dydt(18) = R28;  % IKK_a
dydt(19) = -R29 +R30;  % IL6
dydt(20) = -R31 -R32 +R33 +R34;  % IL6m
dydt(21) = -R35;  % JAK
dydt(22) = R35;  % JAK_a
dydt(23) = -R38 +R39 +R40;  % Myc
dydt(24) = -R21 +R41 -R42 -R43;  % NFkB
dydt(25) = R21;  % NFkBnIKB
dydt(26) = -R44 +R45 +R46;  % PGE2
dydt(27) = -R47;  % PI3K
dydt(28) = R47;  % PI3K_a
dydt(29) = -R48 +R49;  % PIP2
dydt(30) = R48 -R49;  % PIP3
dydt(31) = -R50 -R51;  % PKC
dydt(32) = R50 +R51;  % PKC_a
dydt(33) = -R52 +R53;  % PTEN
dydt(34) = -R54;  % RAS
dydt(35) = R54;  % RAS_a
dydt(36) = -R55;  % STAT3
dydt(37) = R55;  % STAT3_p
dydt(38) = -R62 -R63;  % TNFR1
dydt(39) = R62;  % TNFR1_a
dydt(40) = R63;  % TNFR1_p
dydt(41) = -R56 +R57;  % TNFa
dydt(42) = -R58 -R59 +R60 +R61;  % TNFam
dydt(43) = -R64 +R65;  % TTP
dydt(44) = -R66 +R67 +R68;  % ZFP36
dydt(45) = -R36;  % mTORC1
dydt(46) = R36;  % mTORC1_a
dydt(47) = -R37;  % mTORC2
dydt(48) = R37;  % mTORC2_a

end

% ==========================================
% HELPER FUNCTION: piecewise_std
% ==========================================
function result = piecewise_std(val_if_true, condition, val_if_false)
    if condition
        result = val_if_true;
    else
        result = val_if_false;
    end
end
