%% Simulation Script for EGFR_NFkB_ver_01
% Generated by ODE Model Creator
% Compares MEX simulation vs MATLAB Standard ODE solver

% 경로 설정 (MEX 및 모델 파일 위치 자동 감지)
scriptDir = fileparts(mfilename('fullpath'));
addpath(scriptDir); cd(scriptDir);

%% 1. Model Data
modelName = 'EGFR_NFkB_ver_01';
mexFile = 'EGFR_NFkB_ver_01_mex';
stdOdeFile = 'EGFR_NFkB_ver_01_ode_std';

paramNames = {'Ki_PI3K_PI3K_a_EGFR_p_OSM'; 'Ki_PKC_PKC_a_EGFR_p_OSM'; 'Ki_RAS_RAS_a_EGFR_p_OSM'; 'Ki_TNFR1_TNFR1_p_EGFR_p_OSM'; 'Ki_syn_PTEN_NFkB'; 'Vm_AKT_p_AKT'; 'Vm_AP1_a_AP1'; 'Vm_EGFR_p_EGFR'; 'Vm_ERK_p_ERK'; 'Vm_IKK_a_IKK'; 'Vm_JAK_a_JAK'; 'Vm_PI3K_a_PI3K'; 'Vm_PIP2_PIP3'; 'Vm_PIP3_PIP2'; 'Vm_PKC_a_PKC'; 'Vm_RAS_a_RAS'; 'Vm_STAT3_p_STAT3'; 'Vm_TNFR1_a_TNFR1'; 'Vm_TNFR1_p_TNFR1'; 'Vm_mTORC1_a_mTORC1'; 'Vm_mTORC2_a_mTORC2'; 'Vsyn_AURKAm'; 'Vsyn_COX2m'; 'Vsyn_EGFm'; 'Vsyn_IKBm'; 'Vsyn_IL6m'; 'Vsyn_Myc'; 'Vsyn_NFkB'; 'Vsyn_PGE2'; 'Vsyn_PTEN'; 'Vsyn_TNFam'; 'Vsyn_ZFP36'; 'ka_IKB_NFkB_NFkBnIKB'; 'kalpha_COX2m_NFkB_STAT3_p'; 'kalpha_EGFm_NFkB_STAT3_p'; 'kalpha_IKBm_NFkB_STAT3_p'; 'kalpha_IL6m_NFkB_STAT3_p'; 'kalpha_TNFam_NFkB_STAT3_p'; 'kalpha_ZFP36_NFkB_STAT3_p'; 'kc_AKT_AKT_p_PI3K_a'; 'kc_AKT_AKT_p_mTORC2_a'; 'kc_AP1_AP1_a_ERK_p'; 'kc_EGFR_EGFR_p_EGF'; 'kc_ERK_ERK_p_RAS_a'; 'kc_IKK_IKK_a_AKT_p'; 'kc_IKK_IKK_a_PKC_a'; 'kc_IKK_IKK_a_TNFR1_a'; 'kc_JAK_JAK_a_EGFR_p'; 'kc_JAK_JAK_a_IL6'; 'kc_PI3K_PI3K_a_EGFR_p'; 'kc_PIP2_PIP3_PI3K_a'; 'kc_PIP3_PIP2_PTEN'; 'kc_PKC_PKC_a_EGFR_p'; 'kc_PKC_PKC_a_PGE2'; 'kc_RAS_RAS_a_EGFR_p'; 'kc_STAT3_STAT3_p_JAK_a'; 'kc_TNFR1_TNFR1_a_TNFa'; 'kc_TNFR1_TNFR1_p_EGFR_p'; 'kc_mTORC1_mTORC1_a_AKT_p'; 'kc_mTORC2_mTORC2_a_IKK_a'; 'kd_NFkBnIKB_IKB_NFkB'; 'kdeg_AURKA'; 'kdeg_AURKAm'; 'kdeg_COX2'; 'kdeg_COX2m'; 'kdeg_EGF'; 'kdeg_EGFm'; 'kdeg_IKB'; 'kdeg_IKB_AURKA'; 'kdeg_IKB_IKK_a'; 'kdeg_IKBm'; 'kdeg_IL6'; 'kdeg_IL6m'; 'kdeg_IL6m_TTP'; 'kdeg_Myc'; 'kdeg_NFkB'; 'kdeg_NFkB_TTP'; 'kdeg_PGE2'; 'kdeg_PTEN'; 'kdeg_TNFa'; 'kdeg_TNFam'; 'kdeg_TNFam_TTP'; 'kdeg_TTP'; 'kdeg_ZFP36'; 'ksyn_AURKA_AURKAm'; 'ksyn_AURKAm_Myc'; 'ksyn_COX2_COX2m'; 'ksyn_COX2m_NFkB'; 'ksyn_EGF_EGFm'; 'ksyn_EGFm_AP1_a'; 'ksyn_EGFm_NFkB'; 'ksyn_IKB_IKBm'; 'ksyn_IKBm_NFkB'; 'ksyn_IL6_IL6m'; 'ksyn_IL6m_NFkB'; 'ksyn_Myc_mTORC1_a'; 'ksyn_PGE2_COX2'; 'ksyn_TNFa_TNFam'; 'ksyn_TNFam_NFkB'; 'ksyn_TTP_ZFP36'; 'ksyn_ZFP36_NFkB'; 'OSM_0'; 'OSM_on'};
paramValues = [0.1   0.1   0.1   0.1   0.1  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05   100 10000];

stateNames = {'AKT'; 'AKT_p'; 'AP1'; 'AP1_a'; 'AURKA'; 'AURKAm'; 'COX2'; 'COX2m'; 'EGF'; 'EGFR'; 'EGFR_p'; 'EGFm'; 'ERK'; 'ERK_p'; 'IKB'; 'IKBm'; 'IKK'; 'IKK_a'; 'IL6'; 'IL6m'; 'JAK'; 'JAK_a'; 'Myc'; 'NFkB'; 'NFkBnIKB'; 'PGE2'; 'PI3K'; 'PI3K_a'; 'PIP2'; 'PIP3'; 'PKC'; 'PKC_a'; 'PTEN'; 'RAS'; 'RAS_a'; 'STAT3'; 'STAT3_p'; 'TNFR1'; 'TNFR1_a'; 'TNFR1_p'; 'TNFa'; 'TNFam'; 'TTP'; 'ZFP36'; 'mTORC1'; 'mTORC1_a'; 'mTORC2'; 'mTORC2_a'};
stateValues = [51 91 25 41 76 23  7 29 16 93 81 63 88 81 18 90 54 81 90 32 11 23 43 82 86  0 51 42 22 12 34 95 32 52 71 36 98 97 25 50 30 28  3 61 50  5 28 91];

%% 2. Simulation Settings
fprintf('\n=== Comparison Simulation: MEX vs Standard ODE ===\n');
fprintf('Model: %s\n\n', modelName);

tspan = linspace(0, 15000, 500);
X0 = stateValues(:)';

% +/- 20% 파라미터 변동 (동일한 random seed 사용)
rng(42);  % 재현성을 위한 고정 시드
perturb_range = 0.2;
sim_params = paramValues(:)' .* (1 + (rand(size(paramValues(:)'))-0.5)*2*perturb_range);

%% 3. MEX Simulation
fprintf('Running MEX simulation...\n');
mex_success = false;
try
    tic;
    mex_output = feval(mexFile, tspan, X0, sim_params, []);
    mex_time = toc;
    t_mex = mex_output.time;
    y_mex = mex_output.statevalues;
    mex_success = true;
    fprintf('  MEX completed in %.3f seconds\n', mex_time);
catch ME
    fprintf('  MEX simulation failed: %s\n', ME.message);
    t_mex = []; y_mex = [];
end

%% 4. Standard ODE Simulation (ode15s)
fprintf('Running Standard ODE simulation (ode15s)...\n');
std_success = false;
try
    ode_opts = odeset('RelTol', 1e-6, 'AbsTol', 1e-8);
    tic;
    [t_std, y_std] = ode15s(@(t,y) EGFR_NFkB_ver_01_ode_std(t, y, sim_params(:)), tspan, X0(:), ode_opts);
    std_time = toc;
    std_success = true;
    fprintf('  Standard ODE completed in %.3f seconds\n', std_time);
catch ME
    fprintf('  Standard ODE simulation failed: %s\n', ME.message);
    t_std = []; y_std = [];
end

%% 5. Comparison Visualization
if mex_success || std_success
    figure('Name', ['Comparison: ' modelName], 'Position', [100 100 1400 600]);

    % Subplot 1: MEX Results
    subplot(1,3,1);
    if mex_success
        plot(t_mex, y_mex, 'LineWidth', 1.2);
        title(sprintf('MEX Simulation (%0.3fs)', mex_time));
    else
        text(0.5, 0.5, 'MEX Failed', 'HorizontalAlignment', 'center');
        title('MEX Simulation (Failed)');
    end
    xlabel('Time'); ylabel('Concentration');
    grid on;

    % Subplot 2: Standard ODE Results
    subplot(1,3,2);
    if std_success
        plot(t_std, y_std, 'LineWidth', 1.2);
        title(sprintf('Standard ODE (%0.3fs)', std_time));
    else
        text(0.5, 0.5, 'ODE Failed', 'HorizontalAlignment', 'center');
        title('Standard ODE (Failed)');
    end
    xlabel('Time'); ylabel('Concentration');
    grid on;

    % Subplot 3: Error Comparison (if both succeeded)
    subplot(1,3,3);
    if mex_success && std_success
        % Interpolate to common time points for comparison
        y_mex_interp = interp1(t_mex, y_mex, t_std);
        rel_error = abs(y_mex_interp - y_std) ./ (abs(y_std) + 1e-10) * 100;
        semilogy(t_std, mean(rel_error, 2), 'LineWidth', 1.5);
        title('Mean Relative Error (%)');
        xlabel('Time'); ylabel('Error (%)');
        grid on;
        fprintf('\nMax relative error: %.2e%%\n', max(mean(rel_error, 2)));
    else
        text(0.5, 0.5, 'Cannot Compare', 'HorizontalAlignment', 'center');
        title('Error Comparison (N/A)');
    end

    sgtitle(['Random Parameter Simulation Comparison: ' modelName], 'FontSize', 14);
end

%% 6. Performance Summary
fprintf('\n=== Performance Summary ===\n');
if mex_success && std_success
    fprintf('  MEX Time:          %.3f seconds\n', mex_time);
    fprintf('  Standard ODE Time: %.3f seconds\n', std_time);
    fprintf('  Speed Ratio:       %.1fx (MEX is faster)\n', std_time/mex_time);
end
fprintf('==============================\n');
