classdef Inhibitor < handle
    % INHIBITOR Represents a drug/inhibitor compound in the biological model
    %
    % Properties:
    %   name            - Inhibitor name (e.g., 'FGFR2i', 'PI3Ki', 'AKTi')
    %   initialValue    - Initial concentration
    %   activationTime  - Time when inhibitor is applied
    %
    % Example:
    %   inhibitor = Inhibitor('FGFR2i', 100, 10000);
    %   eqStr = inhibitor.getIQMEquation();

    properties
        name char
        initialValue double = 0
        activationTime double = 0
    end

    methods
        function obj = Inhibitor(name, initialValue, activationTime)
            % Constructor
            % Inputs:
            %   name            - Inhibitor name (required)
            %   initialValue    - Initial concentration (default: 0)
            %   activationTime  - Activation time (default: 0)

            if nargin < 1
                error('Inhibitor:InvalidInput', 'Inhibitor name is required');
            end

            obj.name = name;

            if nargin >= 2
                obj.initialValue = initialValue;
            end

            if nargin >= 3
                obj.activationTime = activationTime;
            end
        end

        function eqStr = getIQMEquation(obj)
            % Generate IQM equation string for this inhibitor
            % Returns: String like "FGFR2i = FGFR2i_0 * piecewiseIQM(1, ge(time, FGFR2i_on), 0)"

            eqStr = sprintf('%s = %s_0 * piecewiseIQM(1, ge(time, %s_on), 0)', ...
                obj.name, obj.name, obj.name);
        end

        function params = getParameterNames(obj)
            % Get parameter names generated by this inhibitor
            % Returns: Cell array of parameter names

            params = {
                sprintf('%s_0', obj.name)
                sprintf('%s_on', obj.name)
            };
        end

        function paramVals = getParameterValues(obj)
            % Get parameter values for this inhibitor
            % Returns: Struct with parameter names and values

            paramVals = struct();
            paramVals.(sprintf('%s_0', obj.name)) = obj.initialValue;
            paramVals.(sprintf('%s_on', obj.name)) = obj.activationTime;
        end

        function isValid = validate(obj)
            % Validate the inhibitor
            % Returns: true if valid, false otherwise

            isValid = true;

            % Name must not be empty
            if isempty(obj.name)
                warning('Inhibitor:EmptyName', 'Inhibitor name cannot be empty');
                isValid = false;
            end

            % Initial value must be non-negative
            if obj.initialValue < 0
                warning('Inhibitor:NegativeValue', ...
                    'Inhibitor "%s" has negative initial value: %f', ...
                    obj.name, obj.initialValue);
                isValid = false;
            end

            % Activation time must be non-negative
            if obj.activationTime < 0
                warning('Inhibitor:NegativeTime', ...
                    'Inhibitor "%s" has negative activation time: %f', ...
                    obj.name, obj.activationTime);
                isValid = false;
            end
        end

        function str = toString(obj)
            % Convert to string representation
            str = sprintf('%s (initial=%g, activation_time=%g)', ...
                obj.name, obj.initialValue, obj.activationTime);
        end

        function disp(obj)
            % Display method
            fprintf('Inhibitor: %s\n', obj.toString());
        end
    end
end
