classdef InputSignal < handle
    % INPUTSIGNAL Represents an external input signal in the biological model
    %
    % Properties:
    %   name            - Signal name (e.g., 'FGF', 'IGF', 'HRG')
    %   initialValue    - Initial concentration
    %   activationTime  - Time when signal is applied
    %
    % Example:
    %   signal = InputSignal('FGF', 10, 5000);
    %   eqStr = signal.getIQMEquation();

    properties
        name char
        initialValue double = 0
        activationTime double = 0
    end

    methods
        function obj = InputSignal(name, initialValue, activationTime)
            % Constructor
            % Inputs:
            %   name            - Signal name (required)
            %   initialValue    - Initial concentration (default: 0)
            %   activationTime  - Activation time (default: 0)

            if nargin < 1
                error('InputSignal:InvalidInput', 'Signal name is required');
            end

            obj.name = name;

            if nargin >= 2
                obj.initialValue = initialValue;
            end

            if nargin >= 3
                obj.activationTime = activationTime;
            end
        end

        function eqStr = getIQMEquation(obj)
            % Generate IQM equation string for this input signal
            % Returns: String like "FGF = FGF_0 * piecewiseIQM(1, ge(time, FGF_on), 0)"

            eqStr = sprintf('%s = %s_0 * piecewiseIQM(1, ge(time, %s_on), 0)', ...
                obj.name, obj.name, obj.name);
        end

        function params = getParameterNames(obj)
            % Get parameter names generated by this input signal
            % Returns: Cell array of parameter names

            params = {
                sprintf('%s_0', obj.name)
                sprintf('%s_on', obj.name)
            };
        end

        function paramVals = getParameterValues(obj)
            % Get parameter values for this input signal
            % Returns: Struct with parameter names and values

            paramVals = struct();
            paramVals.(sprintf('%s_0', obj.name)) = obj.initialValue;
            paramVals.(sprintf('%s_on', obj.name)) = obj.activationTime;
        end

        function isValid = validate(obj)
            % Validate the input signal
            % Returns: true if valid, false otherwise

            isValid = true;

            % Name must not be empty
            if isempty(obj.name)
                warning('InputSignal:EmptyName', 'Input signal name cannot be empty');
                isValid = false;
            end

            % Initial value must be non-negative
            if obj.initialValue < 0
                warning('InputSignal:NegativeValue', ...
                    'Input signal "%s" has negative initial value: %f', ...
                    obj.name, obj.initialValue);
                isValid = false;
            end

            % Activation time must be non-negative
            if obj.activationTime < 0
                warning('InputSignal:NegativeTime', ...
                    'Input signal "%s" has negative activation time: %f', ...
                    obj.name, obj.activationTime);
                isValid = false;
            end
        end

        function str = toString(obj)
            % Convert to string representation
            str = sprintf('%s (initial=%g, activation_time=%g)', ...
                obj.name, obj.initialValue, obj.activationTime);
        end

        function disp(obj)
            % Display method
            fprintf('InputSignal: %s\n', obj.toString());
        end
    end
end
