function dydt = FGFR2_model_ver_01_ode_std(t, y, p)
%% FGFR2_model_ver_01_ode_std - MATLAB Standard ODE Solver Compatible ODE Function
%
% Generated by ODE Model Creator
% Model: FGFR2_model_ver_01
% Date: 16-Jan-2026 15:55:27
%
% Usage:
%   p = FGFR2_model_ver_01_ode_std('parameters');  % Get default parameters
%   y0 = FGFR2_model_ver_01_ode_std('initialvalues');  % Get default initial values
%   [t, y] = ode15s(@(t,y) FGFR2_model_ver_01_ode_std(t, y, p), [0 1000], y0);
%
% State Variables (41):
%   y(1) = AKT
%   y(2) = CDK2
%   y(3) = CDK46
%   y(4) = E2F
%   y(5) = E2FuRB
%   y(6) = ERBB3
%   y(7) = ERK
%   y(8) = FGFR2
%   y(9) = FOXO3
%   y(10) = FRS2
%   y(11) = IGF1R
%   y(12) = IRS
%   y(13) = MEK
%   y(14) = MYC
%   y(15) = PI3K
%   y(16) = RAF
%   y(17) = RAS
%   y(18) = RB
%   y(19) = RBSM
%   y(20) = S6K
%   y(21) = aPI3K
%   y(22) = aRAF
%   y(23) = aRAS
%   y(24) = aRBSM
%   y(25) = amTORC1
%   y(26) = amTORC2
%   y(27) = mTORC1
%   y(28) = mTORC2
%   y(29) = pAKT
%   y(30) = pCDK2
%   y(31) = pCDK46
%   y(32) = pERBB3
%   y(33) = pERK
%   y(34) = pFGFR2
%   y(35) = pFOXO3
%   y(36) = pFRS2
%   y(37) = pIGF1R
%   y(38) = pIRS
%   y(39) = pMEK
%   y(40) = pRB
%   y(41) = pS6K
%

% Handle metadata requests
if nargin == 1 && ischar(t)
    switch lower(t)
        case 'parameters'
            dydt = [0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01   0.1   0.1    10  5000    10  5000    10  5000   500 10000   200 10000   300 10000   400 10000]';
            return;
        case 'parameternames'
            dydt = {'Ki_AKT_pAKT_aPI3K_AKTi'; 'Ki_E2F_RB_E2FuRB_MYC'; 'Ki_ERBB3_pERBB3_HRG_pERK'; 'Ki_FGFR2_pFGFR2_FGF_FGFR2i'; 'Ki_IRS_pIRS_pIGF1R_pS6K'; 'Ki_MEK_pMEK_aRAF_MEKi'; 'Ki_PI3K_aPI3K_pFRS2_PI3Ki'; 'Ki_PI3K_aPI3K_pFRS2_pERK'; 'Ki_PI3K_aPI3K_pIRS_PI3Ki'; 'Ki_RAF_aRAF_aRAS_pAKT'; 'Ki_RAS_aRAS_pFRS2_pERK'; 'Ki_mTORC2_amTORC2_aPI3K_pRB'; 'Vm_aPI3K_PI3K'; 'Vm_aRAF_RAF'; 'Vm_aRAS_RAS'; 'Vm_aRBSM_RBSM'; 'Vm_amTORC1_mTORC1'; 'Vm_amTORC2_mTORC2'; 'Vm_pAKT_AKT'; 'Vm_pCDK2_CDK2'; 'Vm_pCDK46_CDK46'; 'Vm_pERBB3_ERBB3'; 'Vm_pERK_ERK'; 'Vm_pFGFR2_FGFR2'; 'Vm_pFOXO3_FOXO3'; 'Vm_pFRS2_FRS2'; 'Vm_pIGF1R_IGF1R'; 'Vm_pIRS_IRS'; 'Vm_pMEK_MEK'; 'Vm_pRB_RB'; 'Vm_pS6K_S6K'; 'Vsyn_MYC'; 'ka_E2F_RB_E2FuRB'; 'kc_AKT_pAKT_aPI3K'; 'kc_AKT_pAKT_amTORC2'; 'kc_CDK2_pCDK2_E2F'; 'kc_CDK46_pCDK46_MYC'; 'kc_CDK46_pCDK46_aRBSM'; 'kc_ERBB3_pERBB3_FOXO3'; 'kc_ERBB3_pERBB3_HRG'; 'kc_ERBB3_pERBB3_pFGFR2'; 'kc_ERK_pERK_pMEK'; 'kc_FGFR2_pFGFR2_FGF'; 'kc_FGFR2_pFGFR2_FOXO3'; 'kc_FOXO3_pFOXO3_pAKT'; 'kc_FRS2_pFRS2_pFGFR2'; 'kc_IGF1R_pIGF1R_FOXO3'; 'kc_IGF1R_pIGF1R_IGF'; 'kc_IRS_pIRS_pIGF1R'; 'kc_MEK_pMEK_aRAF'; 'kc_PI3K_aPI3K_pERBB3'; 'kc_PI3K_aPI3K_pFRS2'; 'kc_PI3K_aPI3K_pIRS'; 'kc_RAF_aRAF_aRAS'; 'kc_RAS_aRAS_pERBB3'; 'kc_RAS_aRAS_pFRS2'; 'kc_RBSM_aRBSM_MYC'; 'kc_RBSM_aRBSM_amTORC1'; 'kc_RBSM_aRBSM_pERK'; 'kc_RBSM_aRBSM_pS6K'; 'kc_RB_pRB_pCDK2'; 'kc_RB_pRB_pCDK46'; 'kc_S6K_pS6K_amTORC1'; 'kc_mTORC1_amTORC1_pAKT'; 'kc_mTORC1_amTORC1_pCDK46'; 'kc_mTORC2_amTORC2_aPI3K'; 'kc_pFGFR2_FGFR2_pERK'; 'kd_E2FuRB_E2F_RB'; 'kdeg_MYC'; 'IGF_0'; 'IGF_on'; 'FGF_0'; 'FGF_on'; 'HRG_0'; 'HRG_on'; 'FGFR2i_0'; 'FGFR2i_on'; 'PI3Ki_0'; 'PI3Ki_on'; 'AKTi_0'; 'AKTi_on'; 'MEKi_0'; 'MEKi_on'}';
            return;
        case 'initialvalues'
            dydt = [82 91 12 92 63  9 28 55 96 97 15 98 96 49 80 14 42 92 80 96 66  3 85 94 68 76 75 39 66 17 71  3 27  4  9 83 70 32 95  3 44]';
            return;
        case 'statenames'
            dydt = {'AKT'; 'CDK2'; 'CDK46'; 'E2F'; 'E2FuRB'; 'ERBB3'; 'ERK'; 'FGFR2'; 'FOXO3'; 'FRS2'; 'IGF1R'; 'IRS'; 'MEK'; 'MYC'; 'PI3K'; 'RAF'; 'RAS'; 'RB'; 'RBSM'; 'S6K'; 'aPI3K'; 'aRAF'; 'aRAS'; 'aRBSM'; 'amTORC1'; 'amTORC2'; 'mTORC1'; 'mTORC2'; 'pAKT'; 'pCDK2'; 'pCDK46'; 'pERBB3'; 'pERK'; 'pFGFR2'; 'pFOXO3'; 'pFRS2'; 'pIGF1R'; 'pIRS'; 'pMEK'; 'pRB'; 'pS6K'}';
            return;
        otherwise
            error('Unknown request: %s', t);
    end
end

% Use default parameters if not provided
if nargin < 3 || isempty(p)
    p = [0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01   0.1   0.1    10  5000    10  5000    10  5000   500 10000   200 10000   300 10000   400 10000]';
end

% ==========================================
% STATE VARIABLES
% ==========================================
AKT = y(1);
CDK2 = y(2);
CDK46 = y(3);
E2F = y(4);
E2FuRB = y(5);
ERBB3 = y(6);
ERK = y(7);
FGFR2 = y(8);
FOXO3 = y(9);
FRS2 = y(10);
IGF1R = y(11);
IRS = y(12);
MEK = y(13);
MYC = y(14);
PI3K = y(15);
RAF = y(16);
RAS = y(17);
RB = y(18);
RBSM = y(19);
S6K = y(20);
aPI3K = y(21);
aRAF = y(22);
aRAS = y(23);
aRBSM = y(24);
amTORC1 = y(25);
amTORC2 = y(26);
mTORC1 = y(27);
mTORC2 = y(28);
pAKT = y(29);
pCDK2 = y(30);
pCDK46 = y(31);
pERBB3 = y(32);
pERK = y(33);
pFGFR2 = y(34);
pFOXO3 = y(35);
pFRS2 = y(36);
pIGF1R = y(37);
pIRS = y(38);
pMEK = y(39);
pRB = y(40);
pS6K = y(41);

% ==========================================
% PARAMETERS
% ==========================================
Ki_AKT_pAKT_aPI3K_AKTi = p(1);
Ki_E2F_RB_E2FuRB_MYC = p(2);
Ki_ERBB3_pERBB3_HRG_pERK = p(3);
Ki_FGFR2_pFGFR2_FGF_FGFR2i = p(4);
Ki_IRS_pIRS_pIGF1R_pS6K = p(5);
Ki_MEK_pMEK_aRAF_MEKi = p(6);
Ki_PI3K_aPI3K_pFRS2_PI3Ki = p(7);
Ki_PI3K_aPI3K_pFRS2_pERK = p(8);
Ki_PI3K_aPI3K_pIRS_PI3Ki = p(9);
Ki_RAF_aRAF_aRAS_pAKT = p(10);
Ki_RAS_aRAS_pFRS2_pERK = p(11);
Ki_mTORC2_amTORC2_aPI3K_pRB = p(12);
Vm_aPI3K_PI3K = p(13);
Vm_aRAF_RAF = p(14);
Vm_aRAS_RAS = p(15);
Vm_aRBSM_RBSM = p(16);
Vm_amTORC1_mTORC1 = p(17);
Vm_amTORC2_mTORC2 = p(18);
Vm_pAKT_AKT = p(19);
Vm_pCDK2_CDK2 = p(20);
Vm_pCDK46_CDK46 = p(21);
Vm_pERBB3_ERBB3 = p(22);
Vm_pERK_ERK = p(23);
Vm_pFGFR2_FGFR2 = p(24);
Vm_pFOXO3_FOXO3 = p(25);
Vm_pFRS2_FRS2 = p(26);
Vm_pIGF1R_IGF1R = p(27);
Vm_pIRS_IRS = p(28);
Vm_pMEK_MEK = p(29);
Vm_pRB_RB = p(30);
Vm_pS6K_S6K = p(31);
Vsyn_MYC = p(32);
ka_E2F_RB_E2FuRB = p(33);
kc_AKT_pAKT_aPI3K = p(34);
kc_AKT_pAKT_amTORC2 = p(35);
kc_CDK2_pCDK2_E2F = p(36);
kc_CDK46_pCDK46_MYC = p(37);
kc_CDK46_pCDK46_aRBSM = p(38);
kc_ERBB3_pERBB3_FOXO3 = p(39);
kc_ERBB3_pERBB3_HRG = p(40);
kc_ERBB3_pERBB3_pFGFR2 = p(41);
kc_ERK_pERK_pMEK = p(42);
kc_FGFR2_pFGFR2_FGF = p(43);
kc_FGFR2_pFGFR2_FOXO3 = p(44);
kc_FOXO3_pFOXO3_pAKT = p(45);
kc_FRS2_pFRS2_pFGFR2 = p(46);
kc_IGF1R_pIGF1R_FOXO3 = p(47);
kc_IGF1R_pIGF1R_IGF = p(48);
kc_IRS_pIRS_pIGF1R = p(49);
kc_MEK_pMEK_aRAF = p(50);
kc_PI3K_aPI3K_pERBB3 = p(51);
kc_PI3K_aPI3K_pFRS2 = p(52);
kc_PI3K_aPI3K_pIRS = p(53);
kc_RAF_aRAF_aRAS = p(54);
kc_RAS_aRAS_pERBB3 = p(55);
kc_RAS_aRAS_pFRS2 = p(56);
kc_RBSM_aRBSM_MYC = p(57);
kc_RBSM_aRBSM_amTORC1 = p(58);
kc_RBSM_aRBSM_pERK = p(59);
kc_RBSM_aRBSM_pS6K = p(60);
kc_RB_pRB_pCDK2 = p(61);
kc_RB_pRB_pCDK46 = p(62);
kc_S6K_pS6K_amTORC1 = p(63);
kc_mTORC1_amTORC1_pAKT = p(64);
kc_mTORC1_amTORC1_pCDK46 = p(65);
kc_mTORC2_amTORC2_aPI3K = p(66);
kc_pFGFR2_FGFR2_pERK = p(67);
kd_E2FuRB_E2F_RB = p(68);
kdeg_MYC = p(69);
IGF_0 = p(70);
IGF_on = p(71);
FGF_0 = p(72);
FGF_on = p(73);
HRG_0 = p(74);
HRG_on = p(75);
FGFR2i_0 = p(76);
FGFR2i_on = p(77);
PI3Ki_0 = p(78);
PI3Ki_on = p(79);
AKTi_0 = p(80);
AKTi_on = p(81);
MEKi_0 = p(82);
MEKi_on = p(83);

% ==========================================
% INPUT SIGNALS AND INHIBITORS
% ==========================================
IGF = IGF_0 * piecewise_std(1, ge(t, IGF_on), 0);
FGF = FGF_0 * piecewise_std(1, ge(t, FGF_on), 0);
HRG = HRG_0 * piecewise_std(1, ge(t, HRG_on), 0);
FGFR2i = FGFR2i_0 * piecewise_std(1, ge(t, FGFR2i_on), 0);
PI3Ki = PI3Ki_0 * piecewise_std(1, ge(t, PI3Ki_on), 0);
AKTi = AKTi_0 * piecewise_std(1, ge(t, AKTi_on), 0);
MEKi = MEKi_0 * piecewise_std(1, ge(t, MEKi_on), 0);

% ==========================================
% REACTION RATES
% ==========================================
R1 = (kc_FGFR2_pFGFR2_FGF*FGF+kc_FGFR2_pFGFR2_FOXO3*FOXO3)*FGFR2/((1 + Ki_FGFR2_pFGFR2_FGF_FGFR2i*FGFR2i)) - Vm_pFGFR2_FGFR2*pFGFR2;
R2 = (kc_pFGFR2_FGFR2_pERK*pERK)*pFGFR2;
R3 = (kc_ERBB3_pERBB3_HRG*HRG+kc_ERBB3_pERBB3_pFGFR2*pFGFR2+kc_ERBB3_pERBB3_FOXO3*FOXO3)*ERBB3/((1 + Ki_ERBB3_pERBB3_HRG_pERK*pERK)) - Vm_pERBB3_ERBB3*pERBB3;
R4 = (kc_IGF1R_pIGF1R_IGF*IGF+kc_IGF1R_pIGF1R_FOXO3*FOXO3)*IGF1R - Vm_pIGF1R_IGF1R*pIGF1R;
R5 = (kc_FRS2_pFRS2_pFGFR2*pFGFR2)*FRS2 - Vm_pFRS2_FRS2*pFRS2;
R6 = (kc_PI3K_aPI3K_pIRS*pIRS+kc_PI3K_aPI3K_pERBB3*pERBB3)*PI3K/((1 + Ki_PI3K_aPI3K_pIRS_PI3Ki*PI3Ki)) - Vm_aPI3K_PI3K*aPI3K;
R7 = (kc_PI3K_aPI3K_pFRS2*pFRS2)*PI3K/((1 + Ki_PI3K_aPI3K_pFRS2_pERK*pERK)*(1 + Ki_PI3K_aPI3K_pFRS2_PI3Ki*PI3Ki));
R8 = (kc_mTORC2_amTORC2_aPI3K*aPI3K)*mTORC2/((1 + Ki_mTORC2_amTORC2_aPI3K_pRB*pRB)) - Vm_amTORC2_mTORC2*amTORC2;
R9 = (kc_AKT_pAKT_aPI3K*aPI3K+kc_AKT_pAKT_amTORC2*amTORC2)*AKT/((1 + Ki_AKT_pAKT_aPI3K_AKTi*AKTi)) - Vm_pAKT_AKT*pAKT;
R10 = (kc_mTORC1_amTORC1_pAKT*pAKT+kc_mTORC1_amTORC1_pCDK46*pCDK46)*mTORC1 - Vm_amTORC1_mTORC1*amTORC1;
R11 = (kc_S6K_pS6K_amTORC1*amTORC1)*S6K - Vm_pS6K_S6K*pS6K;
R12 = (kc_IRS_pIRS_pIGF1R*pIGF1R)*IRS/((1 + Ki_IRS_pIRS_pIGF1R_pS6K*pS6K)) - Vm_pIRS_IRS*pIRS;
R13 = (kc_RAS_aRAS_pERBB3*pERBB3)*RAS - Vm_aRAS_RAS*aRAS;
R14 = (kc_RAS_aRAS_pFRS2*pFRS2)*RAS/((1 + Ki_RAS_aRAS_pFRS2_pERK*pERK)) - Vm_aRAS_RAS*aRAS;
R15 = (kc_RAF_aRAF_aRAS*aRAS)*RAF/((1 + Ki_RAF_aRAF_aRAS_pAKT*pAKT)) - Vm_aRAF_RAF*aRAF;
R16 = (kc_MEK_pMEK_aRAF*aRAF)*MEK/((1 + Ki_MEK_pMEK_aRAF_MEKi*MEKi)) - Vm_pMEK_MEK*pMEK;
R17 = (kc_ERK_pERK_pMEK*pMEK)*ERK - Vm_pERK_ERK*pERK;
R18 = (kc_FOXO3_pFOXO3_pAKT*pAKT)*FOXO3 - Vm_pFOXO3_FOXO3*pFOXO3;
R19 = (kc_RBSM_aRBSM_pS6K*pS6K+kc_RBSM_aRBSM_amTORC1*amTORC1+kc_RBSM_aRBSM_pERK*pERK+kc_RBSM_aRBSM_MYC*MYC)*RBSM - Vm_aRBSM_RBSM*aRBSM;
R20 = Vsyn_MYC;
R21 = kdeg_MYC*MYC;
R22 = (kc_CDK46_pCDK46_aRBSM*aRBSM+kc_CDK46_pCDK46_MYC*MYC)*CDK46 - Vm_pCDK46_CDK46*pCDK46;
R23 = (ka_E2F_RB_E2FuRB*E2F*RB)/((1 + Ki_E2F_RB_E2FuRB_MYC*MYC)) - kd_E2FuRB_E2F_RB*E2FuRB;
R24 = (kc_RB_pRB_pCDK46*pCDK46+kc_RB_pRB_pCDK2*pCDK2)*RB - Vm_pRB_RB*pRB;
R25 = (kc_CDK2_pCDK2_E2F*E2F)*CDK2 - Vm_pCDK2_CDK2*pCDK2;

% ==========================================
% DIFFERENTIAL EQUATIONS
% ==========================================
dydt = zeros(41, 1);
dydt(1) = -R9;  % AKT
dydt(2) = -R25;  % CDK2
dydt(3) = -R22;  % CDK46
dydt(4) = -R23;  % E2F
dydt(5) = R23;  % E2FuRB
dydt(6) = -R3;  % ERBB3
dydt(7) = -R17;  % ERK
dydt(8) = -R1 +R2;  % FGFR2
dydt(9) = -R18;  % FOXO3
dydt(10) = -R5;  % FRS2
dydt(11) = -R4;  % IGF1R
dydt(12) = -R12;  % IRS
dydt(13) = -R16;  % MEK
dydt(14) = R20 -R21;  % MYC
dydt(15) = -R6 -R7;  % PI3K
dydt(16) = -R15;  % RAF
dydt(17) = -R13 -R14;  % RAS
dydt(18) = -R23 -R24;  % RB
dydt(19) = -R19;  % RBSM
dydt(20) = -R11;  % S6K
dydt(21) = R6 +R7;  % aPI3K
dydt(22) = R15;  % aRAF
dydt(23) = R13 +R14;  % aRAS
dydt(24) = R19;  % aRBSM
dydt(25) = R10;  % amTORC1
dydt(26) = R8;  % amTORC2
dydt(27) = -R10;  % mTORC1
dydt(28) = -R8;  % mTORC2
dydt(29) = R9;  % pAKT
dydt(30) = R25;  % pCDK2
dydt(31) = R22;  % pCDK46
dydt(32) = R3;  % pERBB3
dydt(33) = R17;  % pERK
dydt(34) = R1 -R2;  % pFGFR2
dydt(35) = R18;  % pFOXO3
dydt(36) = R5;  % pFRS2
dydt(37) = R4;  % pIGF1R
dydt(38) = R12;  % pIRS
dydt(39) = R16;  % pMEK
dydt(40) = R24;  % pRB
dydt(41) = R11;  % pS6K

end

% ==========================================
% HELPER FUNCTION: piecewise_std
% ==========================================
function result = piecewise_std(val_if_true, condition, val_if_false)
    if condition
        result = val_if_true;
    else
        result = val_if_false;
    end
end
