%% Simulation Script for FGFR2_model_ver_01
% Generated by ODE Model Creator
% Compares MEX simulation vs MATLAB Standard ODE solver

% 경로 설정 (MEX 및 모델 파일 위치 자동 감지)
scriptDir = fileparts(mfilename('fullpath'));
addpath(scriptDir); cd(scriptDir);

%% 1. Model Data
modelName = 'FGFR2_model_ver_01';
mexFile = 'FGFR2_model_ver_01_mex';
stdOdeFile = 'FGFR2_model_ver_01_ode_std';

paramNames = {'Ki_AKT_pAKT_aPI3K_AKTi'; 'Ki_E2F_RB_E2FuRB_MYC'; 'Ki_ERBB3_pERBB3_HRG_pERK'; 'Ki_FGFR2_pFGFR2_FGF_FGFR2i'; 'Ki_IRS_pIRS_pIGF1R_pS6K'; 'Ki_MEK_pMEK_aRAF_MEKi'; 'Ki_PI3K_aPI3K_pFRS2_PI3Ki'; 'Ki_PI3K_aPI3K_pFRS2_pERK'; 'Ki_PI3K_aPI3K_pIRS_PI3Ki'; 'Ki_RAF_aRAF_aRAS_pAKT'; 'Ki_RAS_aRAS_pFRS2_pERK'; 'Ki_mTORC2_amTORC2_aPI3K_pRB'; 'Vm_aPI3K_PI3K'; 'Vm_aRAF_RAF'; 'Vm_aRAS_RAS'; 'Vm_aRBSM_RBSM'; 'Vm_amTORC1_mTORC1'; 'Vm_amTORC2_mTORC2'; 'Vm_pAKT_AKT'; 'Vm_pCDK2_CDK2'; 'Vm_pCDK46_CDK46'; 'Vm_pERBB3_ERBB3'; 'Vm_pERK_ERK'; 'Vm_pFGFR2_FGFR2'; 'Vm_pFOXO3_FOXO3'; 'Vm_pFRS2_FRS2'; 'Vm_pIGF1R_IGF1R'; 'Vm_pIRS_IRS'; 'Vm_pMEK_MEK'; 'Vm_pRB_RB'; 'Vm_pS6K_S6K'; 'Vsyn_MYC'; 'ka_E2F_RB_E2FuRB'; 'kc_AKT_pAKT_aPI3K'; 'kc_AKT_pAKT_amTORC2'; 'kc_CDK2_pCDK2_E2F'; 'kc_CDK46_pCDK46_MYC'; 'kc_CDK46_pCDK46_aRBSM'; 'kc_ERBB3_pERBB3_FOXO3'; 'kc_ERBB3_pERBB3_HRG'; 'kc_ERBB3_pERBB3_pFGFR2'; 'kc_ERK_pERK_pMEK'; 'kc_FGFR2_pFGFR2_FGF'; 'kc_FGFR2_pFGFR2_FOXO3'; 'kc_FOXO3_pFOXO3_pAKT'; 'kc_FRS2_pFRS2_pFGFR2'; 'kc_IGF1R_pIGF1R_FOXO3'; 'kc_IGF1R_pIGF1R_IGF'; 'kc_IRS_pIRS_pIGF1R'; 'kc_MEK_pMEK_aRAF'; 'kc_PI3K_aPI3K_pERBB3'; 'kc_PI3K_aPI3K_pFRS2'; 'kc_PI3K_aPI3K_pIRS'; 'kc_RAF_aRAF_aRAS'; 'kc_RAS_aRAS_pERBB3'; 'kc_RAS_aRAS_pFRS2'; 'kc_RBSM_aRBSM_MYC'; 'kc_RBSM_aRBSM_amTORC1'; 'kc_RBSM_aRBSM_pERK'; 'kc_RBSM_aRBSM_pS6K'; 'kc_RB_pRB_pCDK2'; 'kc_RB_pRB_pCDK46'; 'kc_S6K_pS6K_amTORC1'; 'kc_mTORC1_amTORC1_pAKT'; 'kc_mTORC1_amTORC1_pCDK46'; 'kc_mTORC2_amTORC2_aPI3K'; 'kc_pFGFR2_FGFR2_pERK'; 'kd_E2FuRB_E2F_RB'; 'kdeg_MYC'; 'IGF_0'; 'IGF_on'; 'FGF_0'; 'FGF_on'; 'HRG_0'; 'HRG_on'; 'FGFR2i_0'; 'FGFR2i_on'; 'PI3Ki_0'; 'PI3Ki_on'; 'AKTi_0'; 'AKTi_on'; 'MEKi_0'; 'MEKi_on'};
paramValues = [0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1   0.1  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01   0.1   0.1    10  5000    10  5000    10  5000   500 10000   200 10000   300 10000   400 10000];

stateNames = {'AKT'; 'CDK2'; 'CDK46'; 'E2F'; 'E2FuRB'; 'ERBB3'; 'ERK'; 'FGFR2'; 'FOXO3'; 'FRS2'; 'IGF1R'; 'IRS'; 'MEK'; 'MYC'; 'PI3K'; 'RAF'; 'RAS'; 'RB'; 'RBSM'; 'S6K'; 'aPI3K'; 'aRAF'; 'aRAS'; 'aRBSM'; 'amTORC1'; 'amTORC2'; 'mTORC1'; 'mTORC2'; 'pAKT'; 'pCDK2'; 'pCDK46'; 'pERBB3'; 'pERK'; 'pFGFR2'; 'pFOXO3'; 'pFRS2'; 'pIGF1R'; 'pIRS'; 'pMEK'; 'pRB'; 'pS6K'};
stateValues = [82 91 12 92 63  9 28 55 96 97 15 98 96 49 80 14 42 92 80 96 66  3 85 94 68 76 75 39 66 17 71  3 27  4  9 83 70 32 95  3 44];

%% 2. Simulation Settings
fprintf('\n=== Comparison Simulation: MEX vs Standard ODE ===\n');
fprintf('Model: %s\n\n', modelName);

tspan = linspace(0, 5000, 500);
X0 = stateValues(:)';

% +/- 20% 파라미터 변동 (동일한 random seed 사용)
rng(42);  % 재현성을 위한 고정 시드
perturb_range = 0.2;
sim_params = paramValues(:)' .* (1 + (rand(size(paramValues(:)'))-0.5)*2*perturb_range);

%% 3. MEX Simulation
fprintf('Running MEX simulation...\n');
mex_success = false;
try
    tic;
    mex_output = feval(mexFile, tspan, X0, sim_params, []);
    mex_time = toc;
    t_mex = mex_output.time;
    y_mex = mex_output.statevalues;
    mex_success = true;
    fprintf('  MEX completed in %.3f seconds\n', mex_time);
catch ME
    fprintf('  MEX simulation failed: %s\n', ME.message);
    t_mex = []; y_mex = [];
end

%% 4. Standard ODE Simulation (ode15s)
fprintf('Running Standard ODE simulation (ode15s)...\n');
std_success = false;
try
    ode_opts = odeset('RelTol', 1e-6, 'AbsTol', 1e-8);
    tic;
    [t_std, y_std] = ode15s(@(t,y) FGFR2_model_ver_01_ode_std(t, y, sim_params(:)), tspan, X0(:), ode_opts);
    std_time = toc;
    std_success = true;
    fprintf('  Standard ODE completed in %.3f seconds\n', std_time);
catch ME
    fprintf('  Standard ODE simulation failed: %s\n', ME.message);
    t_std = []; y_std = [];
end

%% 5. Comparison Visualization
if mex_success || std_success
    figure('Name', ['Comparison: ' modelName], 'Position', [100 100 1400 600]);

    % Subplot 1: MEX Results
    subplot(1,3,1);
    if mex_success
        plot(t_mex, y_mex, 'LineWidth', 1.2);
        title(sprintf('MEX Simulation (%0.3fs)', mex_time));
    else
        text(0.5, 0.5, 'MEX Failed', 'HorizontalAlignment', 'center');
        title('MEX Simulation (Failed)');
    end
    xlabel('Time'); ylabel('Concentration');
    grid on;

    % Subplot 2: Standard ODE Results
    subplot(1,3,2);
    if std_success
        plot(t_std, y_std, 'LineWidth', 1.2);
        title(sprintf('Standard ODE (%0.3fs)', std_time));
    else
        text(0.5, 0.5, 'ODE Failed', 'HorizontalAlignment', 'center');
        title('Standard ODE (Failed)');
    end
    xlabel('Time'); ylabel('Concentration');
    grid on;

    % Subplot 3: Error Comparison (if both succeeded)
    subplot(1,3,3);
    if mex_success && std_success
        % Interpolate to common time points for comparison
        y_mex_interp = interp1(t_mex, y_mex, t_std);
        rel_error = abs(y_mex_interp - y_std) ./ (abs(y_std) + 1e-10) * 100;
        semilogy(t_std, mean(rel_error, 2), 'LineWidth', 1.5);
        title('Mean Relative Error (%)');
        xlabel('Time'); ylabel('Error (%)');
        grid on;
        fprintf('\nMax relative error: %.2e%%\n', max(mean(rel_error, 2)));
    else
        text(0.5, 0.5, 'Cannot Compare', 'HorizontalAlignment', 'center');
        title('Error Comparison (N/A)');
    end

    sgtitle(['Random Parameter Simulation Comparison: ' modelName], 'FontSize', 14);
end

%% 6. Performance Summary
fprintf('\n=== Performance Summary ===\n');
if mex_success && std_success
    fprintf('  MEX Time:          %.3f seconds\n', mex_time);
    fprintf('  Standard ODE Time: %.3f seconds\n', std_time);
    fprintf('  Speed Ratio:       %.1fx (MEX is faster)\n', std_time/mex_time);
end
fprintf('==============================\n');
